### ISSUE TITLE
create a pack with python guide incorrectly references NFT Collection Module

### ISSUE THREAD

**Issue by eabdelmoneim** [nftlabs/guides#22]
At the beginning of the https://thirdweb.com/portal/guides/create-pack-with-python-sdk it mentions creating an NFT Collection module in the Dashboard.  This needs to be changed to creating a Bundle Collection where they've minted at least two NFT's since the Pack Module requires a Bundle module not a NFT Collection Module

**Comment by nachoiacovino** [comment]
Fix here https://github.com/nftlabs/portal/commit/7c0897118f65adcc1598b8f24a97d300d60f56fc
